// cairn — generating the Markdown roadmap from items.
//
// Copyright (C) 2026 Oddur Sigurdsson
//
// This program is free software: you can redistribute it and/or modify it under
// the terms of the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any later
// version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public License along with
// this program.  If not, see <https://www.gnu.org/licenses/>.
use crate::cmd::count_done;
use crate::config::{Category, Config};
use crate::filter::{Ctx, Filter, milestone_rank, resolve};
use crate::item::Item;
use crate::store::Store;
use anyhow::{Context, Result};

pub fn roadmap_markdown(cfg: &Config, store: &Store, items: &[Item]) -> Result<String> {
    let r = &cfg.render;
    let filter = match &r.include {
        Some(expr) => Filter::parse(expr)?,
        None => Filter::default(),
    };
    let ctx = Ctx::new(cfg, items);
    let visible: Vec<&Item> = items.iter().filter(|i| filter.matches(i, &ctx)).collect();

    let mut out = String::new();
    let title = r.title.clone().unwrap_or_else(|| {
        if cfg.project.name.is_empty() {
            "Roadmap".to_string()
        } else {
            format!("{} roadmap", cfg.project.name)
        }
    });
    out.push_str(&format!("# {title}\n\n"));

    if let Some(desc) = &cfg.project.description {
        out.push_str(&format!("{desc}\n\n"));
    }
    if let Some(path) = &r.header {
        out.push_str(read_fragment(cfg, path)?.trim_end());
        out.push_str("\n\n");
    }
    out.push_str(&format!(
        "<!-- generated by cairn; edit the files in `{}` and run `cairn render` -->\n\n",
        cfg.project.dir
    ));

    let groups = group(&ctx, &visible, &r.group_by);
    if groups.is_empty() {
        out.push_str("_No items yet._\n");
    }
    for (key, members) in groups {
        out.push_str(&section_heading(cfg, &r.group_by, &key));
        out.push_str(&meta_line(cfg, &key, &members));
        if let Some(desc) = milestone_description(cfg, &r.group_by, &key) {
            out.push_str(&format!("{desc}\n\n"));
        }
        if r.group_by_status {
            for status in &cfg.statuses {
                let bucket: Vec<&Item> = members
                    .iter()
                    .copied()
                    .filter(|i| i.status() == status.name)
                    .collect();
                if bucket.is_empty() {
                    continue;
                }
                out.push_str(&format!("### {}\n\n", status.display()));
                for i in bucket {
                    out.push_str(&item_line(&ctx, store, i));
                }
                out.push('\n');
            }
        } else {
            for i in &members {
                out.push_str(&item_line(&ctx, store, i));
            }
            out.push('\n');
        }
    }

    if let Some(path) = &r.footer {
        out.push_str(read_fragment(cfg, path)?.trim_end());
        out.push('\n');
    }
    Ok(out)
}

fn section_heading(cfg: &Config, group_by: &str, key: &str) -> String {
    if key.is_empty() {
        return format!("## {}\n\n", unassigned_label(group_by));
    }
    if group_by == "milestone"
        && let Some(m) = cfg.milestone(key)
    {
        return match &m.title {
            Some(t) => format!("## {} — {t}\n\n", m.name),
            None => format!("## {}\n\n", m.name),
        };
    }
    format!("## {key}\n\n")
}

fn unassigned_label(group_by: &str) -> String {
    match group_by {
        "milestone" => "Unscheduled".to_string(),
        "assignee" => "Unassigned".to_string(),
        other => format!("No {other}"),
    }
}

fn meta_line(cfg: &Config, key: &str, members: &[&Item]) -> String {
    let r = &cfg.render;
    let mut bits: Vec<String> = Vec::new();
    if r.progress {
        let done = count_done(cfg, members);
        let total = members.len();
        if total > 0 {
            let pct = (done as f64 / total as f64 * 100.0).round() as u32;
            let filled = (done * 10).div_ceil(total).min(10);
            bits.push(format!(
                "`{}{}` {pct}%",
                "#".repeat(filled),
                "·".repeat(10 - filled)
            ));
            bits.push(format!("{done} of {total} done"));
        }
    }
    if let Some(m) = cfg.milestone(key)
        && let Some(due) = &m.due
    {
        bits.push(format!("due {due}"));
    }
    if bits.is_empty() {
        String::new()
    } else {
        format!("{}\n\n", bits.join(" · "))
    }
}

fn milestone_description(cfg: &Config, group_by: &str, key: &str) -> Option<String> {
    if group_by != "milestone" {
        return None;
    }
    cfg.milestone(key)?.description.clone()
}

fn item_line(ctx: &Ctx, store: &Store, item: &Item) -> String {
    let cfg = ctx.cfg;
    let r = &cfg.render;
    let mut line = String::from("- ");
    if r.checkbox {
        let done = cfg.category(item.status()) == Category::Done;
        line.push_str(if done { "[x] " } else { "[ ] " });
    }
    let title = escape_md(item.title());
    if r.show_ids {
        let id = cfg.format_id(item.id);
        match (&cfg.project.url, r.link_items) {
            (Some(base), true) => {
                let url = format!("{}/{}", base.trim_end_matches('/'), store.rel(&item.path));
                line.push_str(&format!("[`{id}`]({url}) {title}"));
            }
            _ => line.push_str(&format!("`{id}` {title}")),
        }
    } else {
        line.push_str(&title);
    }

    let mut tags: Vec<String> = Vec::new();
    if let Some(k) = item.kind() {
        tags.push(k.to_string());
    }
    for f in cfg.fields.iter().filter(|f| f.column) {
        let v = resolve(item, ctx, &f.name);
        if !v.is_missing() {
            tags.push(v.display());
        }
    }
    tags.extend(item.meta.labels.iter().cloned());
    if !tags.is_empty() {
        line.push_str(&format!(" <sup>{}</sup>", tags.join(" · ")));
    }
    line.push('\n');
    line
}

/// Group items for rendering. Sections come out in a stable, meaningful order:
/// milestones by due date, everything else by first appearance.
fn group<'a>(ctx: &Ctx, items: &[&'a Item], key: &str) -> Vec<(String, Vec<&'a Item>)> {
    let cfg = ctx.cfg;
    let mut groups: Vec<(String, Vec<&'a Item>)> = Vec::new();
    for item in items {
        let value = resolve(item, ctx, key);
        let name = if value.is_missing() {
            String::new()
        } else {
            value.display()
        };
        match groups.iter_mut().find(|(k, _)| *k == name) {
            Some((_, v)) => v.push(item),
            None => groups.push((name, vec![*item])),
        }
    }
    if key == "milestone" {
        groups.sort_by_key(|(k, _)| {
            if k.is_empty() {
                usize::MAX
            } else {
                milestone_rank(cfg, Some(k))
            }
        });
    } else {
        // Empty group always last.
        groups.sort_by_key(|(k, _)| k.is_empty());
    }
    for (_, members) in groups.iter_mut() {
        members.sort_by_key(|i| (cfg.status_index(i.status()), i.id));
    }
    groups
}

fn read_fragment(cfg: &Config, path: &str) -> Result<String> {
    let full = cfg.root.join(path);
    std::fs::read_to_string(&full).with_context(|| format!("reading {}", full.display()))
}

/// Titles land inside Markdown list items; only the characters that would
/// actually break that context are escaped.
fn escape_md(s: &str) -> String {
    s.replace('[', "\\[").replace(']', "\\]")
}
